#ifndef IEQP_VERSION_INCLUDED
#define IEQP_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x)        MAKE_STR_HELPER(x)

#define IEQP_VERSION_MAJOR 11
#define IEQP_VERSION_MINOR 0
#define IEQP_VERSION_PATCH 0
#define IEQP_VERSION_BETA  2
#define IEQP_VERSION_VERSTRING   \
    MAKE_STR(IEQP_VERSION_MAJOR) \
    "." MAKE_STR(IEQP_VERSION_MINOR) "." MAKE_STR(IEQP_VERSION_PATCH) "." MAKE_STR(IEQP_VERSION_BETA)

#endif
